### ISSUE TITLE
Enhancing the code for further use

### ISSUE THREAD

**Issue by patilsk** [srianant/kalman_filter_multi_object_tracking#2]
Is it possible to use this code for speed estimation of vehicle?

**Comment by srianant** [comment]
Yes, its possible. Current implementation of Kalman filter & Hungarian works on every captured frame. For your requirement it require to capture the position and velocity (multiple frames). Found below link on the internet it is a good reference to start with:
https://dsp.stackexchange.com/questions/8860/kalman-filter-for-position-and-velocity-introducing-speed-estimates

**Comment by patilsk** [comment]
Thank you for devoting your prestigious time for clearing my doubt.
