### ISSUE TITLE
where can I get the "TrackingBugs.mp4" for the execution 

### ISSUE THREAD

**Issue by adioshun** [srianant/kalman_filter_multi_object_tracking#7]
Thanks for the code sharing. 

It's helpful for me. I'd like to execute the code. For this, could you share the  **TrackingBugs.mp4** that was used for this code. 

Thanks.

**Comment by adioshun** [comment]
I found it. Is this the same file that you used for the tracking? 

https://github.com/Smorodov/Multitarget-tracker/blob/master/data/TrackingBugs.mp4

**Comment by srianant** [comment]
I think so. Can’t share as I don’t have the copyright.
