### ISSUE TITLE
Extension to vehicle detection

### ISSUE THREAD

**Issue by kabef94** [srianant/kalman_filter_multi_object_tracking#8]
Hi !  Great work .. I wanted to use the same code for vehicle tracking.. but it makes random  detections . I tried to change a few parameters but i'm not getting any results.

What are the changes i need to make in order to use this for vehicle detection?

**Comment by srianant** [comment]
Hi @kabef94,
To help understand the problem better. Would recommend try following steps. 
1) Try tracking fewer objects (say..a video with 2 cars or 2 rolling balls) and its speed (probably display them in bounding box corner as text for easy evaluation) with default parameter values?
2) For detector try increasing the blob_radius_thresh, depending on the blob radius.
3) For tracker try decreasing distance threshold.
Hope above steps helps in better detection and tracking. Good luck.

**Comment by kabef94** [comment]
I had already done the first two but even the third one does not help.. the detections look like this(PFA).. i even tried changing the parameters for canny edge detection an thresholding as well.. nothing is working. Sorry for bothering you but any more ideas??
![untitled](https://user-images.githubusercontent.com/43745200/47890762-52b68280-de76-11e8-9cde-6079afe3f6af.png)

**Comment by srianant** [comment]
Hope you followed below pipeline.
Convert2Gray --> BackgroundSubtract --> EdgeDetection --> FindContours.
Given your video frame it looks like backgroundSubtraction & edgeDetection may need some improvements. Capturing frames after EdgeDetection might help analyze. This repo was developed and tested using video with static background. You may want to consider other techniques to find contour or detect objects in general, if your background is constantly changing. Hope this helps.
